### PR TITLE
adjust the center of anim

### PR DESCRIPTION
**Pull request by qiaoyunrui**
# Smoother animation 

Hello, I have used your animation library, but I found the animation is a bit stiff, and fab's revealOn animation can not make transformView all covered out. So, I think of a way, is to revealOn center placed in the center of transformView, so that the animation transition is smoother. You can look at my code, I hope to be able to adopt, thank you.

你好，我已经使用过你的动画库了，但是我发现你的动画有点僵直，而且fab的revealOn动画不能把transformView全部覆盖掉。所以，我想了一个方法，就是把revealOn的中心放置在transformView的中心，从而使这个动画过渡更加平滑了。你可以看一下我的代码，希望能够采纳，谢谢你。

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Can you put gif animation file or movie? 🙇

**Comment by qiaoyunrui** [comment]
Here is.

**Comment by qiaoyunrui** [comment]
Thanks for your reply.

**Comment by konifar** [comment]
Cool! Thanks for your cooperation.
Maybe it's okay. Let me check this change on my device.

**Comment by qiaoyunrui** [comment]
Okey

**Comment by konifar** [comment]
Checked!! Thanks for your great contribution!!

**Pull request merged**
